### ISSUE TITLE
[BUG] Wrong info tab displayed in PDF reader

### ISSUE THREAD

**Issue by FeralFlora** [pablogila/Zotero-Shadow#1]
This theme plugin has the same bug as the Zotero night plugin, namely that the info tab will not stay syncronized with the current pdf in the pdf reader. This causes potential editing errors and confusion/inconvenience.

See: https://github.com/tefkah/zotero-night/issues/88

**Comment by pablogila** [comment]
Couldn't replicate the bug on Windows. What OS are you using?

**Comment by FeralFlora** [comment]
> Couldn't replicate the bug on Windows. What OS are you using?

I'm also using Window (10), and Zotero 6.0.27.
