### ISSUE TITLE
UI gaps, Toolbar, dialogs and some text fields missing theming on Flatpak

### ISSUE THREAD

**Issue by jrom99** [pablogila/Zotero-Shadow#2]
- There are some gaps in the main panel that didn't get darkened, for which I added `#zotero-pane` as a selector.
- It seems that the current toolbar selector only works when there are tabs present.
- Some dialogs also feature white text on white background.
- While both the top search field and the tag selector input field have dark text on dark background, the advanced search dialog input field works normally.

## Before `#zotero-pane` selector:
![Screenshot from 2023-08-03 01-10-30](https://github.com/pablogila/ZoteroShadow/assets/47498278/9d7b4107-92c2-4e82-aa45-259d360c63cb)

## After `#zotero-pane` selector:
![Screenshot from 2023-08-03 01-11-58](https://github.com/pablogila/ZoteroShadow/assets/47498278/0fa664c1-c74e-4617-aa87-f4406fb4eddf)

## After a tab is opened (the toolbar is now darkened, and the tab's title is white on white)
![Screenshot from 2023-08-03 01-12-57](https://github.com/pablogila/ZoteroShadow/assets/47498278/2e5acea0-5c75-4d5b-8118-e4e480ef358c)

## Settings dialog:
![Screenshot from 2023-08-03 01-17-11](https://github.com/pablogila/ZoteroShadow/assets/47498278/36f3826e-aa69-454a-84d7-da8d3ab1ca11)

## Advanced search dialog:
![Screenshot from 2023-08-03 01-17-20](https://github.com/pablogila/ZoteroShadow/assets/47498278/a6dcf1f8-2df1-4695-9289-bdf08d8ed6b7)

**Comment by pablogila** [comment]
Are you using Windows? Currently it is the only OS supported. To get a dark mode on Linux, it is recommended to use the Flatpak version of Zotero, which includes it by default.
